---
abstract: 'A Catalyst model base-class for using WWW::MenuGrinder'
author:
  - 'Andrew Rodland <andrew@hbslabs.com>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.11
generated_by: 'Dist::Zilla version 1.100711'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Catalyst-Model-MenuGrinder
requires:
  Catalyst: 5.7012
  Scope::Guard: 0
  WWW::MenuGrinder: 0.04
version: 0.05
