---
abstract: 'A Catalyst model base-class for using WWW::MenuGrinder'
author:
  - 'Andrew Rodland <andrew@hbslabs.com>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.31
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200003, CPAN::Meta::Converter version 2.102400'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Catalyst-Model-MenuGrinder
requires:
  Catalyst: 5.8
  Moose: 0
  Scope::Guard: 0
  WWW::MenuGrinder: 0.04
version: 0.06
